---
# Source: apps/templates/app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ds-knowledge-store
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: ds-lab-1

  # Source of the application manifests
  source:
    repoURL: git@github.com:Adarga-Ltd/k8s-ds-labs.git
    targetRevision: HEAD
    path: environments/ds-labs/ds-lab-1/services/ds-knowledge-store

  # Destination cluster and namespace to deploy the application
  destination:
    name: ds-lab-1
    namespace: ds-knowledge-store

# Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
