---
# Source: apps/templates/app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ds-lab-1-seldon
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: ds-lab-1

  # Source of the application manifests
  source:
    repoURL: git@github.com:Adarga-Ltd/k8s-ds-labs.git
    targetRevision: HEAD
    path: environments/ds-labs/ds-lab-1/services/seldon

  # Destination cluster and namespace to deploy the application
  destination:
    name: ds-lab-1
    namespace: seldon

# Sync policy
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
