---
apiVersion: batch/v1
kind: Job
metadata:
  name: doc2vec-pipeline
  namespace: pach-feed-1-12
spec:
  template:
    spec:
      containers:
      - name: pachctl-internal
        image: pachyderm/pachctl:1.12.3
        imagePullPolicy: Always
        command:
          - sh
          - -c
          - 'pachctl config update context --namespace pach-feed-1-12 && pachctl update pipeline -f /config/doc2vec.json'
        resources:
          requests:
            cpu: 10m
            memory: 1500Ki
        volumeMounts:
          - name: pipe-config
            mountPath: /config
      restartPolicy: Never
      serviceAccount: internal-pachctl
      volumes:
        - name: pipe-config
          configMap:
            name: doc2vec-pipeline-config
