---
apiVersion: v1
kind: Service
metadata:
  name: neptune-proxy
  namespace: default
  labels:
    app: neptune-proxy
spec:
  ports:
    - name: neptune
      port: 8182
      targetPort: 8182
      protocol: TCP
  selector:
    app: neptune-proxy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: neptune-proxy-config
  namespace: default
  labels:
    app: neptune-proxy
data:
  envoy.yaml: |-
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 9901

    static_resources:
      listeners:
        - name: neptune
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 8182
          filter_chains:
            - filters:
              - name: envoy.filters.network.http_connection_manager
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                  stat_prefix: ingress_http
                  access_log:
                    - name: envoy.access_loggers.file
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                        path: /dev/stdout
                  http_filters:
                    - name: envoy.filters.http.router
                  route_config:
                    name: local_route
                    virtual_hosts:
                      - name: local_service
                        domains: ["*"]
                        routes:
                          - match:
                              prefix: "/"
                            route:
                              host_rewrite_literal: ${NEPTUNE_ENDPOINT}
                              cluster: neptune_cluster
      clusters:
        - name: neptune_cluster
          connect_timeout: 2s
          type: LOGICAL_DNS
          load_assignment:
            cluster_name: neptune_cluster
            endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: ${NEPTUNE_ENDPOINT}
                        port_value: ${NEPTUNE_PORT}
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
              sni: ${NEPTUNE_ENDPOINT}
    layered_runtime:
      layers:
        - name: static
          static_layer:
            envoy:
              resource_limits:
                listener:
                  neptune:
                    connection_limit: 100
            overload:
              global_downstream_max_connections: 100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neptune-proxy
  namespace: default
  labels:
    app: neptune-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neptune-proxy
  template:
    metadata:
      labels:
        app: neptune-proxy
    spec:
      restartPolicy: Always
      initContainers:
      - name: envsubst
        image: eu.gcr.io/adarga-docker/toolbox/envsubst
        imagePullPolicy: IfNotPresent
        env:
        - name: ENVSUBST
          value: /template/envoy.yaml,/subst
        - name: NEPTUNE_ENDPOINT
          value: ds-lab-1-wikidata.cluster-csr9h8eq61nj.eu-west-2.neptune.amazonaws.com
        - name: NEPTUNE_PORT
          value: "8182"
        volumeMounts:
        - name: config-tmpl
          mountPath: /template
        - name: config-dir
          mountPath: /subst
      containers:
      - name: envoyproxy
        image: envoyproxy/envoy:v1.17-latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: neptune
          containerPort: 8182
        resources:
          requests:
            cpu: 20m
            memory: 15Mi
        volumeMounts:
        - name: config-dir
          mountPath: /etc/envoy
          readOnly: true
      volumes:
      - name: config-tmpl
        configMap:
          name: neptune-proxy-config
          defaultMode: 0744
      - name: config-dir
        emptyDir: {}
