---
apiVersion: v1
kind: Pod
metadata:
  name: blazegraph-bastion
spec:
  restartPolicy: Always
  containers:
  - name: main
    image: eu.gcr.io/adarga-docker/toolbox/swiss-army:0.1.7
    imagePullPolicy: IfNotPresent
    command:
      - /bin/bash
      - -xc
      - |
        echo 'alias blazegraph="ssh -i /ssh/key.pem ec2-user@10.12.13.73"' >>.bash_aliases
        sleep infinity
    volumeMounts:
    - name: ssh-key
      mountPath: /ssh
  volumes:
  - name: ssh-key
    secret:
      secretName: blazegraph-ssh-key
