kind: PachydermPipeline
apiVersion: adarga.ai/v1alpha1
metadata:
  name: base-entity-recogniser
  namespace: pach-feed-1-12
spec:
  name: base-entity-recogniser
  description: "Base entity recogniser pipeline. (Controller)"
  transform:
    cmd: ["python3", "EntityRecogniser.py"]
    image: $(BASE_ENTITY_RECOGNISER_IMAGE)
    env:
      - name: SERVICE_URL_BASE
        value: "http://ds-base-entity-recogniser-ner-predict-default.seldon.svc.cluster.local:8000"
      - name: SERVICE_ENDPOINT
        value: "api/v1.0/predictions"
      - name: SENTENCES_REPO
        value: "/pfs/sentence-extraction"
      - name: OUTPUT_REPO
        value: "/pfs/out"

  input:
    pfs:
      repo: "sentence-extraction"
      glob: "/*/(*).jsonl"
      branch: "master"

  egress: "s3://adarga-ds-lab-1-pachyderm-egress/feed-base-entity-recogniser"
  enable_stats: false
