kind: PachydermPipeline
apiVersion: adarga.ai/v1alpha1
metadata:
  name: ds-entity-cleaning
  namespace: pach-feed-1-12
spec:
  name: ds-entity-cleaning
  description: "Entity cleaner pipeline. (Controller)"
  transform:
    cmd: ["python3", "EntityCleaner.py"]
    image: $(ENTITY_CLEANER_IMAGE)
    env:
      - name: SERVICE_URL_BASE
        value: "http://ds-entity-cleaning-predict-default.seldon.svc.cluster.local:8000"
      - name: SERVICE_ENDPOINT
        value: "api/v1.0/predictions"
      - name: NER_REPO
        value: "/pfs/base-entity-recogniser"
      - name: OUTPUT_REPO
        value: "/pfs/out"

  input:
    pfs:
      repo: "base-entity-recogniser"
      glob: "/*/(*).jsonl"
      branch: "master"

  enable_stats: true
