---
# Source: ds-knowledge-store/templates/publish-model.yaml
kind: PachydermPipeline
apiVersion: adarga.ai/v1alpha1
metadata:
  name: "bertee-model-weight-publisher"
  namespace: pach-feed-1-12
spec:
  name: "bertee-model-weight-publisher"
  description: "bertee weights model to ecr publishing"
  transform:
    cmd: ["/publish-model.sh"]
    image: eu.gcr.io/adarga-docker/ds-knowledge-store-publish-model:1.24.0

    env:
      - name: AMW_DECRIPTION
        value: Adarga trained weights for bertee classification
      - name: ORAS_REPO_HEAD
        value: 382855879375.dkr.ecr.eu-west-2.amazonaws.com/amw/bertee-weights-
  input:
    pfs:
      repo: bertee-weights
      glob: "/*"
      branch: "master"
  enable_stats: true
---
# Source: ds-knowledge-store/templates/transform.yaml
kind: PachydermPipeline
apiVersion: adarga.ai/v1alpha1
metadata:
  name: document-standardisation
  namespace: pach-feed-1-12
spec:
  name: document-standardisation
  description: document-standardisation ds-knowledge-store transform
  transform:
    cmd: ["python3", "-m", "transforms", "document-standardisation"]
    image: eu.gcr.io/adarga-docker/ds-knowledge-store-transform:1.24.0

    
  input:
    pfs:
      repo: ingress-dev-1-spout
      glob: "/*/*"
      branch: "master"

  enable_stats: true
---
# Source: ds-knowledge-store/templates/transform.yaml
kind: PachydermPipeline
apiVersion: adarga.ai/v1alpha1
metadata:
  name: sentence-extraction
  namespace: pach-feed-1-12
spec:
  name: sentence-extraction
  description: sentence-extraction ds-knowledge-store transform
  transform:
    cmd: ["python3", "-m", "transforms", "sentence-extraction"]
    image: eu.gcr.io/adarga-docker/ds-knowledge-store-transform:1.24.0

    
    env:
      - name: SERVICE_URL_BASE
        value: http://sentence-extraction-default.seldon.svc.cluster.local:8000
      - name: SERVICE_ENDPOINT
        value: "api/v1.0/predictions"
    
  input:
    pfs:
      repo: document-standardisation
      glob: "/*/*"
      branch: "master"

  enable_stats: true
---
# Source: ds-knowledge-store/templates/transform.yaml
kind: PachydermPipeline
apiVersion: adarga.ai/v1alpha1
metadata:
  name: naive-event-detection
  namespace: pach-feed-1-12
spec:
  name: naive-event-detection
  description: naive-event-detection ds-knowledge-store transform
  transform:
    cmd: ["python3", "-m", "transforms", "naive-event-detection"]
    image: eu.gcr.io/adarga-docker/ds-knowledge-store-transform:1.24.0

    
    env:
      - name: SERVICE_URL_BASE
        value: http://naive-event-detection-default.seldon.svc.cluster.local:8000
      - name: SERVICE_ENDPOINT
        value: "api/v1.0/predictions"
    
  input:
    pfs:
      repo: sentence-extraction
      glob: "/*/*"
      branch: "master"

  enable_stats: true
---
# Source: ds-knowledge-store/templates/transform.yaml
kind: PachydermPipeline
apiVersion: adarga.ai/v1alpha1
metadata:
  name: event-mention-coreference
  namespace: pach-feed-1-12
spec:
  name: event-mention-coreference
  description: event-mention-coreference ds-knowledge-store transform
  transform:
    cmd: ["python3", "-m", "transforms", "event-mention-coreference"]
    image: eu.gcr.io/adarga-docker/ds-knowledge-store-transform:1.24.0

    
    env:
      - name: SERVICE_URL_BASE
        value: http://event-mention-coreference-default.seldon.svc.cluster.local:8000
      - name: SERVICE_ENDPOINT
        value: "api/v1.0/predictions"
    
  input:
    pfs:
      repo: event-detection
      glob: "/*/*"
      branch: "master"

  enable_stats: true
---
# Source: ds-knowledge-store/templates/transform.yaml
kind: PachydermPipeline
apiVersion: adarga.ai/v1alpha1
metadata:
  name: mention-extraction
  namespace: pach-feed-1-12
spec:
  name: mention-extraction
  description: mention-extraction ds-knowledge-store transform
  transform:
    cmd: ["python3", "-m", "transforms", "mention-extraction"]
    image: eu.gcr.io/adarga-docker/ds-knowledge-store-transform:1.24.0

    
    env:
      - name: SERVICE_URL_BASE
        value: http://mention-extraction-default.seldon.svc.cluster.local:8000
      - name: SERVICE_ENDPOINT
        value: "api/v1.0/predictions"
    
  input:
    pfs:
      repo: sentence-extraction
      glob: "/*/*"
      branch: "master"

  enable_stats: true
---
# Source: ds-knowledge-store/templates/transform.yaml
kind: PachydermPipeline
apiVersion: adarga.ai/v1alpha1
metadata:
  name: mention-coreference
  namespace: pach-feed-1-12
spec:
  name: mention-coreference
  description: mention-coreference ds-knowledge-store transform
  transform:
    cmd: ["python3", "-m", "transforms", "mention-coreference"]
    image: eu.gcr.io/adarga-docker/ds-knowledge-store-transform:1.24.0

    
    env:
      - name: SERVICE_URL_BASE
        value: http://mention-coreference-default.seldon.svc.cluster.local:8000
      - name: SERVICE_ENDPOINT
        value: "api/v1.0/predictions"
    
  input:
    pfs:
      repo: sentence-extraction
      glob: "/*/*"
      branch: "master"

  enable_stats: true
---
# Source: ds-knowledge-store/templates/transform.yaml
kind: PachydermPipeline
apiVersion: adarga.ai/v1alpha1
metadata:
  name: mention-typing
  namespace: pach-feed-1-12
spec:
  name: mention-typing
  description: mention-typing ds-knowledge-store transform
  transform:
    cmd: ["python3", "-m", "transforms", "mention-typing"]
    image: eu.gcr.io/adarga-docker/ds-knowledge-store-transform:1.24.0

    
    env:
      - name: SERVICE_URL_BASE
        value: http://mention-typing-default.seldon.svc.cluster.local:8000
      - name: SERVICE_ENDPOINT
        value: "api/v1.0/predictions"
    
  input:
    pfs:
      repo: sentence-extraction
      glob: "/*/*"
      branch: "master"

  enable_stats: true
---
# Source: ds-knowledge-store/templates/transform.yaml
kind: PachydermPipeline
apiVersion: adarga.ai/v1alpha1
metadata:
  name: svo-extraction
  namespace: pach-feed-1-12
spec:
  name: svo-extraction
  description: svo-extraction ds-knowledge-store transform
  transform:
    cmd: ["python3", "-m", "transforms", "svo-extraction"]
    image: eu.gcr.io/adarga-docker/ds-knowledge-store-transform:1.24.0

    
    env:
      - name: SERVICE_URL_BASE
        value: http://svo-extraction-default.seldon.svc.cluster.local:8000
      - name: SERVICE_ENDPOINT
        value: "api/v1.0/predictions"
    
  input:
    pfs:
      repo: sentence-extraction
      glob: "/*/*"
      branch: "master"

  enable_stats: true
