kind: PachydermPipeline
apiVersion: adarga.ai/v1alpha1
metadata:
  name: extractive-summarisation
  namespace: pach-feed-1-12
spec:
  name: extractive-summarisation
  description: "extractive summarisation pipeline. Calls Seldon, Returns summary. (Controller)"
  transform:
    cmd: ["python3", "ExtractiveSummarisationPipeline.py"]
    image: $(EXTRACTIVE_SUMMARISATION_IMAGE)
    env:
      - name: SERVICE_URL_BASE
        value: "http://extractive-summarisation-default.seldon.svc.cluster.local:8000"
      - name: SERVICE_ENDPOINT
        value: "api/v1.0/predictions"
      - name: INPUT_REPO
        value: "/pfs/clean-ingress-feed"
      - name: OUTPUT_REPO
        value: "/pfs/out"
  input:
    pfs:
      repo: "clean-ingress-feed"
      glob: "/*/*"
      branch: "master"

  egress: "s3://adarga-ds-lab-1-pachyderm-egress/feed-extractive-summarisation"
  enable_stats: false
