kind: PachydermPipeline
apiVersion: adarga.ai/v1alpha1
metadata:
  name: future-signals-classifier
  namespace: pach-feed-1-12
spec:
  name: future-signals-classifier
  description: "Future signals classification pipeline. (Controller)"
  transform:
    cmd: ["python3", "ZeroShotClassifierPipeline.py"]
    image: $(FUTURE_SIGNALS_IMAGE)
    env:
      - name: SERVICE_URL_BASE
        value: "http://future-signals-predict-default.seldon.svc.cluster.local:8000"
      - name: SERVICE_ENDPOINT
        value: "api/v1.0/predictions"
      - name: SENTENCES_REPO
        value: "/pfs/text-classification-labels/PMESII_labels.json"
      - name: EVENTS_REPO
        value: "/pfs/clean-ingress-feed"
      - name: OUTPUT_REPO
        value: "/pfs/out"

  input:
    join:
      - repo: "sentence-extraction"
        glob: "/*/(*).jsonl"
        branch: "master"

      - repo: "event-detector"
        glob: "/*/(*).jsonl"
        branch: "master"

  egress: "s3://adarga-ds-lab-1-pachyderm-egress/feed-future-signals-classifier"
  enable_stats: false
