kind: PachydermPipeline
apiVersion: adarga.ai/v1alpha1
metadata:
  name: mention-typer
  namespace: pach-feed-1-12
spec:
  name: mention-typer
  description: "Mention typing.(Controller)"
  transform:
    cmd: ["python3", "-m", "service", "mention-typing"]
    image: eu.gcr.io/adarga-docker/ds-knowledge-store-transform:from_kustomize
    env:
      - name: SERVICE_URL_BASE
        value: "http://mention-typer-default.seldon.svc.cluster.local:8000"
      - name: SERVICE_ENDPOINT
        value: "api/v1.0/predictions"

  input:
    pfs:
      repo: "sentence-extraction"
      glob: "/*/*"
      branch: "master"

  egress: "s3://adarga-ds-lab-1-pachyderm-egress/feed-mention-typer"
  enable_stats: false
