kind: PachydermPipeline
apiVersion: adarga.ai/v1alpha1
metadata:
  name: mention-grouper
  namespace: pach-feed-1-12
spec:
  name: mention-grouper
  description: "Mention Grouping. (Controller)"
  transform:
    cmd: ["python3", "-m", "service", "mention-grouper"]
    image: eu.gcr.io/adarga-docker/ds-knowledge-store:from_kustomize
    env:
      - name: SERVICE_URL_BASE
        value: "http://mentiongrouper-default.seldon.svc.cluster.local:8000"
      - name: SERVICE_ENDPOINT
        value: "api/v1.0/predictions"
  input:
    pfs:
      repo: "sentence-extraction"
      glob: "/*/*"
      branch: "master"

  egress: "s3://adarga-ds-lab-1-pachyderm-egress/mention-grouper"
  enable_stats: false
