apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ner-training.yaml
nameSuffix: 0.0.1
configMapGenerator:
- files:
  - ner-training.json
  name: ner-training-pipeline-config
  namespace: pach-training-1-12
