apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pachyderm-core.yaml
  - pachctl-internal-role.yaml
  - pachd-internal-lb.yaml
  - ./jobs
  - ./pipelines
images:
- name: eu.gcr.io/adarga-docker/infra/qd-pipeline-controller
  newTag: 1.2.0
