apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pach-feed-1-12
configMapGenerator:
- envs:
  - pachyderm-controller.properties
  name: pachyderm-controller-config


resources:
- pachyderm-core.yaml
- pachctl-internal-role.yaml
- pachd-internal-lb.yaml
- pachyderm-controller.yaml
- ./pipelines
images:
- name: eu.gcr.io/adarga-docker/infra/qd-pipeline-controller
  newTag: 1.4.1
