apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-pachctl
  namespace: pach-feed-1-12
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pachctl-ops
  namespace: pach-feed-1-12
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/portforward
    verbs:
      - get
      - list
      - delete
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pachctl-ops
  namespace: pach-feed-1-12
subjects:
  - kind: ServiceAccount
    name: internal-pachctl
roleRef:
  kind: Role
  name: pachctl-ops
  apiGroup: rbac.authorization.k8s.io
---
