apiVersion: v1
kind: ServiceAccount
metadata:
  name: qd-pipeline-controller
  namespace: pach-feed-1-12
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: qd-pipeline-controller
  namespace: pach-feed-1-12
rules:
  - apiGroups: ["adarga.ai"]
    resources:
      - pachydermpipelines
      - pachydermpipelines/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroup: [""]
    resources:
      - replicationcontrollers
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qd-pipeline-controller
  namespace: pach-feed-1-12
subjects:
  - kind: ServiceAccount
    name: qd-pipeline-controller
roleRef:
  kind: Role
  name: qd-pipeline-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qd-pipeline-controller
  namespace: pach-feed-1-12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qd-pipeline-controller
  template:
    metadata:
      labels:
        app: qd-pipeline-controller
    spec:
      serviceAccount: qd-pipeline-controller
      containers:
        - name: controller
          image: eu.gcr.io/adarga-docker/infra/qd-pipeline-controller:from_kustomize
          imagePullPolicy: Always
          env:
            - name: PACHYDERM_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: pachyderm-controller-config
                  key: PACHYDERM_ADDRESS

            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

          resources:
            requests:
              cpu: 10m
              memory: 100Mi
