---
apiVersion: kci.rocks/v1alpha1
kind: Database
metadata:
  name: benchmark-db
  namespace: pach-training-1-12
spec:
  secretName: benchmark-db-credentials
  instance: pdb-instance
  deletionProtected: true
  backup:
    enable: false
    cron: 0 0 * * *
  extensions:
    - uuid-ossp
    - plpgsql
