apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- benchmark-db.yaml
- pachyderm-core.yaml
- pachctl-internal-role.yaml
- pachd-internal-lb.yaml
- deployment.yaml
- ingress.yaml
- service.yaml
- ./jobs
images:
- name: eu.gcr.io/adarga-docker/ds-custom-entity-recogniser-dashboard
  newName: eu.gcr.io/adarga-docker/ds-custom-entity-recogniser-dashboard
  newTag: 1.2.0-beta2
