kind: SeldonDeployment
apiVersion: machinelearning.seldon.io/v1
metadata:
  name: doc2vec
  namespace: seldon
  labels: {}
spec:
  name: doc2vec
  protocol: seldon
  annotations: {}
  predictors:
    - name: default
      graph:
        name: doc2vec
        type: MODEL
        parameters:
          - name: 'model_data'
            value: '/models/models/doc2vec'
            type: STRING

      componentSpecs:
        - spec:
            containers:
              - name: doc2vec
                image: eu.gcr.io/adarga-docker/document-doc2vec-component-doc2vec:from_kustomize
                env:
                  - name: LOG_LEVEL
                    value: INFO

                volumeMounts:
                  - mountPath: /models
                    name: model-data

            initContainers:
              - name: doc2vec-initialiser
                image: eu.gcr.io/adarga-docker/toolbox/oras:0.10.0-b
                imagePullPolicy: IfNotPresent
                env:
                  - name: AMWVERSION
                    value: 1.0
                  - name: AWS_ECR
                    value: 382855879375.dkr.ecr.eu-west-2.amazonaws.com
                command:
                  - /bin/sh
                  - -xc
                  - |
                    export HOME=/tmp # to workaround privileged execution issues
                    oras-aws-ecr-login
                    echo "downloading model"
                    cd /models
                    oras pull ${AWS_ECR}/amw/doc2vec/:v1.0 --allow-all
                    echo "done"

                volumeMounts:
                  - mountPath: /models
                    name: model-data

            volumes:
              - emptyDir: {}
                name: model-data

          replicas: 1
