apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- word-count-pipeline.yaml
nameSuffix: 1.3.8
configMapGenerator:
- files:
  - word-count-pipeline.json
  name: word-count-pipeline-config
  namespace: pach-experiments-1-12
