kind: SeldonDeployment
apiVersion: machinelearning.seldon.io/v1
metadata:
  name: event-argument-classification
  namespace: seldon
  labels: {}
spec:
  name: event-argument-classification
  protocol: seldon
  annotations: {}
  predictors:
    - name: default
      graph:
        name: event-argument-classification
        type: MODEL
      componentSpecs:
        - spec:
            containers:
              - name: event-argument-classifier
                image: eu.gcr.io/adarga-docker/ds-knowledge-store-seldon-bertee:from_kustomize
                env:
                  - name: LOG_LEVEL
                    value: INFO
                  - name: MODEL_NAME
                    value: EventArgumentClassification
                  - name: MODEL_DATA
                    value: /models
                volumeMounts:
                  - mountPath: /models
                    name: model-data
            initContainers:
              - name: bertee-event-argument-classification-initialiser
                image: eu.gcr.io/adarga-docker/toolbox/oras:0.10.0-b
                imagePullPolicy: IfNotPresent
                env:
                  - name: PACH_JOB_ID
                    valueFrom:
                      configMapKeyRef:
                        name: adarga-model-weights-config
                        key: PACH_JOB_ID
                  - name: AWS_ECR
                    valueFrom:
                      configMapKeyRef:
                        name: adarga-model-weights-config
                        key: AWS_ECR
                command:
                  - /bin/sh
                  - -xc
                  - |
                    export HOME=/tmp # to workaround privileged execution issues
                    oras-aws-ecr-login
                    echo "downloading model"
                    cd /models
                    oras pull ${AWS_ECR}/amw/bertee-weights-event-argument-classification:${PACH_JOB_ID} --allow-all
                    tar -xf model.tgz
                    echo "done"
                volumeMounts:
                  - mountPath: /models
                    name: model-data
            volumes:
              - emptyDir: {}
                name: model-data
          replicas: 1