apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- mention-typer.yaml
- mention-extraction.yaml
- mention-grouper.yaml
- sentence-extraction.yaml
- svo-extraction.yaml
- event-detector.yaml
- event-grouper.yaml
- event-trigger-detector.yaml
- event-classification.yaml
- event-argument-classification.yaml
images:
- name: eu.gcr.io/adarga-docker/ds-knowledge-store-seldon
  newName: eu.gcr.io/adarga-docker/ds-knowledge-store-seldon
  newTag: 1.23.4
- name: eu.gcr.io/adarga-docker/ds-knowledge-store-seldon-bertee
  newName: eu.gcr.io/adarga-docker/ds-knowledge-store-seldon-bertee
  newTag: 1.23.4
