apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- mention-typer.yaml
- mention-extraction.yaml
- mention-grouper.yaml
- sentence-extraction.yaml
- svo-extraction.yaml
- event-detector.yaml
images:
- name: eu.gcr.io/adarga-docker/ds-knowledge-store-seldon
  newName: eu.gcr.io/adarga-docker/ds-knowledge-store-seldon
  newTag: 1.7.1
nameSuffix: 1.3.8
