kind: SeldonDeployment
apiVersion: machinelearning.seldon.io/v1
metadata:
  name: sentence-extraction
  namespace: seldon
  labels: {}
spec:
  name: sentence-extraction
  protocol: seldon
  transport: grpc
  annotations: {}
  predictors:
    - name: default
      graph:
        name: sentence-extraction
        type: MODEL
      componentSpecs:
        - spec:
            containers:
              - name: sentence-extraction
                image: eu.gcr.io/adarga-docker/ds-knowledge-store-seldon:from_kustomize
                env:
                  - name: LOG_LEVEL
                    value: INFO
                  - name: MODEL_NAME
                    value: SentenceExtraction
                  - name: MODEL_DATA
                    value: /models/models/nltk-punkt-english/english.pickle
                volumeMounts:
                  - mountPath: /models
                    name: model-data
            initContainers:
              - name: nltk-initialiser
                image: eu.gcr.io/adarga-docker/toolbox/oras:0.10.0-b
                imagePullPolicy: IfNotPresent
                env:
                  - name: OMWVERSION
                    valueFrom:
                      configMapKeyRef:
                        name: opensource-model-weights-config
                        key: OMWVERSION
                  - name: AWS_ECR
                    valueFrom:
                      configMapKeyRef:
                        name: opensource-model-weights-config
                        key: AWS_ECR
                command:
                  - /bin/sh
                  - -xc
                  - |
                    export HOME=/tmp # to workaround privileged execution issues
                    oras-aws-ecr-login
                    echo "downloading Punkt"
                    cd /models
                    oras pull ${AWS_ECR}/omw/nltk-punkt-english:${OMWVERSION} --allow-all
                    echo "done"
                volumeMounts:
                  - mountPath: /models
                    name: model-data
            volumes:
              - emptyDir: {}
                name: model-data
          replicas: 1