kind: SeldonDeployment
apiVersion: machinelearning.seldon.io/v1
metadata:
  name: adarga-hello-ml-world-wordcount
  namespace: seldon
  labels: {}
spec:
  name: adarga-hello-ml-world-wordcount
  protocol: seldon
  annotations: {}
  predictors:
    - name: default
      graph:
        name: adarga-hello-ml-world-wordcount
        type: MODEL

      componentSpecs:
        - spec:
            containers:
              - name: adarga-hello-ml-world-wordcount
                image: eu.gcr.io/adarga-docker/adarga-hello-ml-world-wordcount:from_kustomize
                env:
                  - name: LOG_LEVEL
                    value: INFO
                  - name: TRACING
                    value: '1'
                  - name: JAEGER_AGENT_HOST
                    valueFrom:
                      fieldRef:
                        fieldPath: status.hostIP
                  - name: JAEGER_AGENT_PORT
                    value: '5775'
                  - name: JAEGER_SAMPLER_TYPE
                    value: const
                  - name: JAEGER_SAMPLER_PARAM
                    value: '1'
                  - name: JAEGER_ENDPOINT
                    value: jaeger-collector.observability.svc.cluster.local
      replicas: 1
