# Source: seldon-single-model/templates/seldondeployment.json
kind: SeldonDeployment
apiVersion: machinelearning.seldon.io/v1
metadata:
  name: seldon-hw
  namespace: seldon
  labels: {}
spec:
  name: seldon-hw
  protocol: seldon
  annotations: {}
  predictors:
    - name: default
      graph:
        name: model
        type: MODEL
      componentSpecs:
        - spec:
            containers:
              - name: model
                image: eu.gcr.io/adarga-workbench-dev/seldon-hw:0.0.1
                env:
                  - name: LOG_LEVEL
                    value: INFO
                resources:
                  requests:
                    memory: 1Mi
      replicas: 1
