apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./knowledge-store
  - ./base-entity-recogniser
  - ./text-classification
  - ./future-references
  - ./doc2vec
  - ./sentencification
  - ./document-clustering
  - ./document-clustering-db.yaml
  - ./extractive-summarisation
  - ./rule-entity-recogniser
  - ./entity-cleaner
configurations:
- kustomizeconfig/seldondeployment.yaml
configMapGenerator:
- name: opensource-model-weights-config
  envs:
  - opensource-model-weights.properties
  namespace: seldon
- name: adarga-model-weights-config
  envs:
  - adarga-model-weights.properties
  namespace: seldon
