apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
- kustomizeconfig/seldondeployment.yaml
resources:
- mention-typer.yaml
- mention-extraction.yaml
- mention-grouper.yaml
- sentence-extraction.yaml
- svo-extraction.yaml
- adarga-hello-ml-world-wordcount.yaml
images:
- name: eu.gcr.io/adarga-docker/adarga-hello-ml-world-wordcount
  newTag: 1.3.23
- name: eu.gcr.io/adarga-docker/ds-knowledge-store-seldon
  newName: eu.gcr.io/adarga-docker/ds-knowledge-store-seldon
  newTag: 1.3.8
nameSuffix: v1
configMapGenerator:
- envs:
  - opensource-model-weights.properties
  name: opensource-model-weights-config
  namespace: seldon
