apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./knowledge-store
  - ./base-entity-recogniser
  - ./text-classification
configurations:
- kustomizeconfig/seldondeployment.yaml
configMapGenerator:
- envs:
  - opensource-model-weights.properties
  name: opensource-model-weights-config
  namespace: seldon
