resources:
- hello-world.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: eu.gcr.io/adarga-workbench-dev/seldon-hw
  newName: eu.gcr.io/adarga-workbench-dev/seldon-hw
  newTag: 0.0.1
