resources:
- sentence-extraction.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: eu.gcr.io/adarga-docker/ds-knowledge-store-seldon
  newName: eu.gcr.io/adarga-docker/ds-knowledge-store-seldon
  newTag: 1.0.1
