kind: SeldonDeployment
apiVersion: machinelearning.seldon.io/v1
metadata:
  name: sentence-extraction
  namespace: seldon
  labels: {}
spec:
  name: sentence-extraction
  protocol: seldon
  transport: grpc
  annotations: {}
  predictors:
    - name: default
      graph:
        name: sentence-extraction
        type: MODEL
#        children:
#          - name: svo-extraction-post
#            type: MODEL
      componentSpecs:
        - spec:
            containers:
              - name: sentence-extraction
                image: eu.gcr.io/adarga-docker/ds-knowledge-store-seldon:from_kustomize
                env:
                  - name: LOG_LEVEL
                    value: INFO
                  - name: MODEL_NAME
                    value: SentenceExtractor
                  - name: MODEL_DATA
                    value: ./data/nltk-weights/english.pickle
#              - name: svo-extraction-post
#                image: spacy:0.1
#                env:
#                  - name: LOG_LEVEL
#                    value: INFO
#                  - name: MODEL_NAME
#                    value: SvoExtractionPost
                resources:
                  requests:
                    memory: 1Mi
      replicas: 1
