---
apiVersion: v1
kind: Namespace
metadata:
  name: pach-experiments-1-12
---
apiVersion: v1
kind: Namespace
metadata:
  name: pach-feed-1-12
---
apiVersion: v1
kind: Namespace
metadata:
  name: pach-training-1-12
