---
apiVersion: batch/v1
kind: Job
metadata:
  name: pachctl-fsck-nofix
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: internal-pachctl
      containers:
      - name: pachctl
        image: pachyderm/pachctl:1.12.5
        imagePullPolicy: Always
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        command:
          - /bin/sh
          - -ecx
          - |
            pachctl config update context --namespace $NAMESPACE
            pachctl version
            pachctl fsck --verbose --no-color
