apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- document-cluster-predict.yaml
images:
- name: eu.gcr.io/adarga-docker/document-clustering-db-migration
  newName: eu.gcr.io/adarga-docker/document-clustering-db-migration
  newTag: 1.3.4
- name: eu.gcr.io/adarga-docker/document-clustering-predict
  newName: eu.gcr.io/adarga-docker/document-clustering-predict
  newTag: 1.3.4
