apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- zero-shot-predict.yaml
images:
- name: eu.gcr.io/adarga-docker/ds-text-classification-zero_shot_predict
  newName: eu.gcr.io/adarga-docker/ds-text-classification-zero_shot_predict
  newTag: 1.2.4
