kind: SeldonDeployment
apiVersion: machinelearning.seldon.io/v1
metadata:
  name: zero-shot-predict
  namespace: seldon
  labels: {}
spec:
  name: zero-shot-predict
  protocol: seldon
  annotations: {}
  predictors:
    - name: default
      graph:
        name: zero-shot-predict
        type: MODEL
        parameters:
          - name: 'model_name_or_path'
            value: '/models/models/facebook-bart-large-mnli'
            type: STRING
          - name: 'device'
            value: '0'
            type: STRING

      componentSpecs:
        - spec:
            containers:
              - name: zero-shot-predict
                image: eu.gcr.io/adarga-docker/ds-text-classification-zero_shot_predict:from_kustomize
                resources:
                  limits:
                    memory: 15G
                    nvidia.com/gpu: 1
                  requests:
                    cpu: 0.1
                    memory: 15G
                    nvidia.com/gpu: 1
                env:
                  - name: TRANSFORMERS_CACHE
                    value: "/tmp/.transformers_cache"
                  - name: LOG_LEVEL
                    value: INFO

                volumeMounts:
                  - mountPath: /models
                    name: model-data

            initContainers:
               - name: bart-initialiser
                 image: eu.gcr.io/adarga-docker/toolbox/oras:0.10.0-b
                 imagePullPolicy: IfNotPresent
                 env:
                   - name: OMWVERSION
                     valueFrom:
                       configMapKeyRef:
                         name: opensource-model-weights-config
                         key: OMWVERSION
                   - name: AWS_ECR
                     valueFrom:
                       configMapKeyRef:
                         name: opensource-model-weights-config
                         key: AWS_ECR
                 command:
                   - /bin/sh
                   - -xc
                   - |
                     export HOME=/tmp # to workaround privileged execution issues
                     oras-aws-ecr-login
                     echo "downloading model"
                     cd /models
                     oras pull ${AWS_ECR}/omw/facebook-bart-large-mnli:${OMWVERSION} --allow-all

                     echo "done"

                 volumeMounts:
                   - mountPath: /models
                     name: model-data
            volumes:
              - emptyDir: {}
                name: model-data

          replicas: 1
