kind: SeldonDeployment
apiVersion: machinelearning.seldon.io/v1
metadata:
  name: ds-entity-cleaner
  namespace: seldon
  labels: {}
spec:
  name: ds-entity-cleaner
  protocol: seldon
  annotations: {}
  predictors:
    - name: default
      graph:
        name: ds-entity-cleaner
        type: MODEL
      componentSpecs:
        - spec:
            containers:
              - name: entity-cleaner
                image: eu.gcr.io/adarga-docker/ds-entity-cleaner:from_kustomize
                env:
                  - name: TRANSFORMERS_CACHE
                    value: "/tmp/.transformers_cache"
                resources:
                  requests:
                    memory: 1Gi
                volumeMounts:
                  - mountPath: /models
                    name: model-data
            initContainers:
              - name: spacy-initialiser
                image: eu.gcr.io/adarga-docker/toolbox/oras:0.10.0-b
                imagePullPolicy: IfNotPresent
                env:
                  - name: OMWVERSION
                    valueFrom:
                      configMapKeyRef:
                        name: opensource-model-weights-config
                        key: OMWVERSION
                  - name: AWS_ECR
                    valueFrom:
                      configMapKeyRef:
                        name: opensource-model-weights-config
                        key: AWS_ECR

                command:
                  - /bin/sh
                  - -xc
                  - |
                    export HOME=/tmp # to workaround privileged execution issues
                    oras-aws-ecr-login
                    echo "downloading model"
                    cd /models
                    oras pull ${AWS_ECR}/omw/tner-xlm-roberta-base-ontonotes5:${OMWVERSION} --allow-all
                    echo "done"

                volumeMounts:
                  - mountPath: /models
                    name: model-data
            volumes:
              - emptyDir: {}
                name: model-data
              - name: ner-config
                configMap:
                  name: ner-base
      replicas: 1
