apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pachctl-internal-role.yaml
  - word-count-pipeline.yaml
configMapGenerator:
- name: word-count-pipeline-config
  namespace: pach-experiments-1-12
  files:
  - word-count-pipeline.json
