apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pachctl-internal-role.yaml
  - hello-world-pipeline.yaml
configMapGenerator:
- name: hello-world-pipeline-config
  namespace: pach-experiments-1-12
  files:
  - hello-world-pipeline.json
