apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pach-experiments-1-12
configMapGenerator:
- envs:
  - pachyderm-controller.properties
  name: pachyderm-controller-config
resources:
- pachyderm-core.yaml
- pachctl-internal-role.yaml
- pachd-internal-lb.yaml
# - pachyderm-controller.yaml
# - ./jobs
#- ./pipelines
images:
- name: 382855879375.dkr.ecr.eu-west-2.amazonaws.com/infra/qd-pipeline-controller
  newTag: 1-1-0
- name: eu.gcr.io/adarga-docker/infra/qd-pipeline-controller
  newTag: 1.8.0
