apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pachyderm-core.yaml
  - pachctl-internal-role.yaml
  - pachd-internal-lb.yaml
  - pachyderm-controller.yaml
  - ./jobs
  - ./pipelines
