---
apiVersion: batch/v1
kind: Job
metadata:
  name: word-count-pipeline
  namespace: pach-experiments-1-12
spec:
  template:
    spec:
      containers:
      - name: pachctl-internal
        image: pachyderm/pachctl:1.12.3
        imagePullPolicy: Always
        command:
          - pachctl
          - update
          - /config/word-count-pipeline.json
        resources:
          requests:
            cpu: 10m
            memory: 1500Ki
        volumeMounts:
          - name: pipe-config
            mountPath: /config
      restartPolicy: Never
      serviceAccount: internal-pachctl
      volumes:
        - name: pipe-config
          configMap:
            name: word-count-pipeline-config
